# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used for the demo environment

version: "1"

mcp:
  enabled: true
  operations_dir: operations
  exclude_mutations: false
  graph_name: my-graph
  expose_schema: true
  enable_arbitrary_operations: true
  listen_addr: :5025

events:
  providers:
    nats:
      - id: default
        url: "nats://localhost:4222"
      - id: my-nats
        url: "nats://localhost:4222"
    kafka:
      - id: my-kafka
        brokers:
          - "localhost:9092"