# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used for the demo environment

version: "1"

dev_mode: true

access_logs:
  enabled: true
  output:
    stdout:
      enabled: true
  router:
    fields:
      - key: "req-content-length"
        value_from:
          request_header: "Content-Length"
      - key: "res-content-length"
        value_from:
          response_header: "Content-Length"
#  subgraphs:
#    enabled: true
#    fields:
#      - key: "req-content-length"
#        value_from:
#          request_header: "Content-Length"
#      - key: "res-content-length"
#        value_from:
#          response_header: "Content-Length"

events:
  providers:
    nats:
      - id: default
        url: "nats://localhost:4222"
      - id: my-nats
        url: "nats://localhost:4222"
    kafka:
      - id: my-kafka
        brokers:
          - "localhost:9092"